dist: xenial
language: go

go:
  - "1.13"

env:
  - GO111MODULE=on

jobs:
  include:
    - name: "Unit Tests"
      env: FLAGS=""
    - name: "Unit Test + Race detection"
      env: FLAGS="-race"

script:
  - cd go/iden3mobile
  - go test -v -count=1 $FLAGS ./...
